-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 19:19:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`osoba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`osoba` ;

CREATE TABLE IF NOT EXISTS `mydb`.`osoba` (
  `oID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `datum_rodjenja` DATE NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`oID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kupac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kupac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kupac` (
  `osoba_oID` INT UNSIGNED NOT NULL,
  `clan_od` DATE NULL,
  PRIMARY KEY (`osoba_oID`),
  INDEX `fk_kupac_osoba_idx` (`osoba_oID` ASC) VISIBLE,
  CONSTRAINT `fk_kupac_osoba`
    FOREIGN KEY (`osoba_oID`)
    REFERENCES `mydb`.`osoba` (`oID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prodavac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prodavac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prodavac` (
  `osoba_oID` INT UNSIGNED NOT NULL,
  `datum_zaposlenja` DATE NULL,
  `licenca_farmaceut` VARCHAR(45) NULL,
  PRIMARY KEY (`osoba_oID`),
  INDEX `fk_kupac_osoba_idx` (`osoba_oID` ASC) VISIBLE,
  CONSTRAINT `fk_kupac_osoba0`
    FOREIGN KEY (`osoba_oID`)
    REFERENCES `mydb`.`osoba` (`oID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tip_leka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tip_leka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tip_leka` (
  `tipID` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  PRIMARY KEY (`tipID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proizvodjac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proizvodjac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proizvodjac` (
  `pID` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL,
  `adresa` VARCHAR(45) NULL,
  PRIMARY KEY (`pID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lek` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lek` (
  `lekID` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL,
  `tip_leka_tipID` INT NOT NULL,
  `proizvodjac_pID` INT NOT NULL,
  PRIMARY KEY (`lekID`),
  INDEX `fk_lek_tip_leka1_idx` (`tip_leka_tipID` ASC) VISIBLE,
  INDEX `fk_lek_proizvodjac1_idx` (`proizvodjac_pID` ASC) VISIBLE,
  CONSTRAINT `fk_lek_tip_leka1`
    FOREIGN KEY (`tip_leka_tipID`)
    REFERENCES `mydb`.`tip_leka` (`tipID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lek_proizvodjac1`
    FOREIGN KEY (`proizvodjac_pID`)
    REFERENCES `mydb`.`proizvodjac` (`pID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jedinica_mere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jedinica_mere` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jedinica_mere` (
  `jID` INT NOT NULL AUTO_INCREMENT,
  `jedinica` VARCHAR(45) NULL,
  PRIMARY KEY (`jID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ambalaza_leka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ambalaza_leka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ambalaza_leka` (
  `lek_lekID` INT NOT NULL,
  `jedinica_mere_jID` INT NOT NULL,
  `cena` DECIMAL(6,2) NULL,
  PRIMARY KEY (`lek_lekID`, `jedinica_mere_jID`),
  INDEX `fk_ambalaza_leka_lek1_idx` (`lek_lekID` ASC) VISIBLE,
  INDEX `fk_ambalaza_leka_jedinica_mere1_idx` (`jedinica_mere_jID` ASC) VISIBLE,
  CONSTRAINT `fk_ambalaza_leka_lek1`
    FOREIGN KEY (`lek_lekID`)
    REFERENCES `mydb`.`lek` (`lekID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ambalaza_leka_jedinica_mere1`
    FOREIGN KEY (`jedinica_mere_jID`)
    REFERENCES `mydb`.`jedinica_mere` (`jID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doktor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doktor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doktor` (
  `licenca_br` VARCHAR(45) NULL,
  `osoba_oID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`osoba_oID`),
  INDEX `fk_doktor_osoba1_idx` (`osoba_oID` ASC) VISIBLE,
  CONSTRAINT `fk_doktor_osoba1`
    FOREIGN KEY (`osoba_oID`)
    REFERENCES `mydb`.`osoba` (`oID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recept` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recept` (
  `recID` INT NOT NULL AUTO_INCREMENT,
  `ambalaza_leka_lek_lekID` INT NOT NULL,
  `ambalaza_leka_jedinica_mere_jID` INT NOT NULL,
  `doktor_osoba_oID` INT UNSIGNED NOT NULL,
  `kupac_osoba_oID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`recID`),
  INDEX `fk_recept_ambalaza_leka1_idx` (`ambalaza_leka_lek_lekID` ASC, `ambalaza_leka_jedinica_mere_jID` ASC) VISIBLE,
  INDEX `fk_recept_doktor1_idx` (`doktor_osoba_oID` ASC) VISIBLE,
  INDEX `fk_recept_kupac1_idx` (`kupac_osoba_oID` ASC) VISIBLE,
  CONSTRAINT `fk_recept_ambalaza_leka1`
    FOREIGN KEY (`ambalaza_leka_lek_lekID` , `ambalaza_leka_jedinica_mere_jID`)
    REFERENCES `mydb`.`ambalaza_leka` (`lek_lekID` , `jedinica_mere_jID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recept_doktor1`
    FOREIGN KEY (`doktor_osoba_oID`)
    REFERENCES `mydb`.`doktor` (`osoba_oID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recept_kupac1`
    FOREIGN KEY (`kupac_osoba_oID`)
    REFERENCES `mydb`.`kupac` (`osoba_oID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`izdati_recept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`izdati_recept` ;

CREATE TABLE IF NOT EXISTS `mydb`.`izdati_recept` (
  `datum_izdavanja` DATE NULL,
  `prodavac_osoba_oID` INT UNSIGNED NOT NULL,
  `recept_recID` INT NOT NULL,
  PRIMARY KEY (`recept_recID`),
  INDEX `fk_izdao_prodavac1_idx` (`prodavac_osoba_oID` ASC) VISIBLE,
  INDEX `fk_izdao_recept1_idx` (`recept_recID` ASC) VISIBLE,
  CONSTRAINT `fk_izdao_prodavac1`
    FOREIGN KEY (`prodavac_osoba_oID`)
    REFERENCES `mydb`.`prodavac` (`osoba_oID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_izdao_recept1`
    FOREIGN KEY (`recept_recID`)
    REFERENCES `mydb`.`recept` (`recID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`narucio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`narucio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`narucio` (
  `kupac_osoba_oID` INT UNSIGNED NOT NULL,
  `izdati_recept_recept_recID` INT NOT NULL,
  PRIMARY KEY (`izdati_recept_recept_recID`),
  INDEX `fk_narucio_kupac1_idx` (`kupac_osoba_oID` ASC) VISIBLE,
  INDEX `fk_narucio_izdati_recept1_idx` (`izdati_recept_recept_recID` ASC) VISIBLE,
  CONSTRAINT `fk_narucio_kupac1`
    FOREIGN KEY (`kupac_osoba_oID`)
    REFERENCES `mydb`.`kupac` (`osoba_oID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narucio_izdati_recept1`
    FOREIGN KEY (`izdati_recept_recept_recID`)
    REFERENCES `mydb`.`izdati_recept` (`recept_recID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventar` (
  `kolicina` INT NULL,
  `ambalaza_leka_lek_lekID` INT NOT NULL,
  `ambalaza_leka_jedinica_mere_jID` INT NOT NULL,
  PRIMARY KEY (`ambalaza_leka_lek_lekID`, `ambalaza_leka_jedinica_mere_jID`),
  INDEX `fk_inventar_ambalaza_leka1_idx` (`ambalaza_leka_lek_lekID` ASC, `ambalaza_leka_jedinica_mere_jID` ASC) VISIBLE,
  CONSTRAINT `fk_inventar_ambalaza_leka1`
    FOREIGN KEY (`ambalaza_leka_lek_lekID` , `ambalaza_leka_jedinica_mere_jID`)
    REFERENCES `mydb`.`ambalaza_leka` (`lek_lekID` , `jedinica_mere_jID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`osoba`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`osoba` (`oID`, `ime`, `prezime`, `datum_rodjenja`, `username`, `password`) VALUES (1, 'Djordje', 'Karisic', '2000-10-18', 'djordje34', 'djordje34');
INSERT INTO `mydb`.`osoba` (`oID`, `ime`, `prezime`, `datum_rodjenja`, `username`, `password`) VALUES (2, 'DJordje', 'DJordjevic', '1999-10-10', 'asdasdasd123', 'dasdasd431');
INSERT INTO `mydb`.`osoba` (`oID`, `ime`, `prezime`, `datum_rodjenja`, `username`, `password`) VALUES (3, 'Gavrilo', 'Gavrilovic', '1389-06-13', 'gavrilo123', '123gravilo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`kupac`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`kupac` (`osoba_oID`, `clan_od`) VALUES (1, '2010-01-01');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`prodavac`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`prodavac` (`osoba_oID`, `datum_zaposlenja`, `licenca_farmaceut`) VALUES (3, '2000-01-01', '8658234');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`tip_leka`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`tip_leka` (`tipID`, `naziv`) VALUES (1, 'antibiotik');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`proizvodjac`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`proizvodjac` (`pID`, `ime`, `adresa`) VALUES (1, 'Galenika', 'D. Maksimovic 34');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`lek`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`lek` (`lekID`, `ime`, `tip_leka_tipID`, `proizvodjac_pID`) VALUES (1, 'Hemomicin', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`jedinica_mere`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`jedinica_mere` (`jID`, `jedinica`) VALUES (1, '3 tablete po 500mg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ambalaza_leka`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ambalaza_leka` (`lek_lekID`, `jedinica_mere_jID`, `cena`) VALUES (1, 1, 200);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`doktor`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`doktor` (`licenca_br`, `osoba_oID`) VALUES ('874593295', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`recept`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`recept` (`recID`, `ambalaza_leka_lek_lekID`, `ambalaza_leka_jedinica_mere_jID`, `doktor_osoba_oID`, `kupac_osoba_oID`) VALUES (1, 1, 1, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`izdati_recept`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`izdati_recept` (`datum_izdavanja`, `prodavac_osoba_oID`, `recept_recID`) VALUES ('2022-01-09', 3, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`narucio`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`narucio` (`kupac_osoba_oID`, `izdati_recept_recept_recID`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`inventar`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`inventar` (`kolicina`, `ambalaza_leka_lek_lekID`, `ambalaza_leka_jedinica_mere_jID`) VALUES (10, 1, 1);

COMMIT;

